uint8 HARDWARE_JETSON = 1

builtin_interfaces/Time timestamp
uint8 hardware_type	
float32 ram_used
float32 ram_total
uint8 free_ram_blocks
float32 iram_used
float32 iram_total
float32 iram_size
float32 swap_used
float32 swap_total
float32 swap_cached
uint8 cpus_num
string[] cpu_names
float32[] cpu_frequencies
float32[] cpu_loads
float32 gr3d_used
float32 gr3d_frequency
float32 emc_used
float32 emc_frequency
uint8 temp_nums
string[] temp_names
float32[] temp_values
uint8 pwr_nums
string[] pwr_names
float32[] pwr_inst
float32[] pwr_avg
